# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibonacci_numbers
  a = 1
  b = 2

  total = b # b= 2, even number.

  while b < 4_000_000
    c = b
    b = a + b
    a = c
    if b % 2 == 0
      total += b
    end
  end
  puts total
end

even_fibonacci_numbers

#Answer: 4613732
